istambul fix
1Hive/token-request-app pull request #91
Opened 2019-11-05 03:03 UTC by rperez89

This is because of bingen comment 

`Because of those problems with EIP-1884, you may consider not using `transfer`. See:
<https://github.com/aragon/aragonOS/pull/551>
<https://github.com/aragon/aragon-apps/issues/1017>
<https://diligence.consensys.net/blog/2019/09/stop-using-soliditys-transfer-now/>`

2019-11-05 13:39 UTC, willjgriff requested changes
I don't think there's any risk from reentrancy here, as we delete a struct which is required at the start of each function. However, I would suggest adding a reentrancy guard, eg the modifier `nonReentrant` which is in the `AragonApp` contract, to each function that does a `call.value()`.

2019-11-05 13:39 UTC, willjgriff commented on contracts/TokenRequest.sol
> +    string private constant ERROR_ETH_TRANSFER_FAILED = "TOKEN_REQUEST_ETH_TRANSFER_FAILED";
Can we add a test for this new error message?

2019-11-06 02:51 UTC, rperez89 commented
@willjgriff i did as you requested a test for when the ETH transfer fails, but for when we are doing the refund i couldn't make it work because i am setting the msg.sender as mockErc20.address in order to make it fail but i am getting this other error `Error: Returned error: sender account not recognized` i just let the last test commented so you can see what i am talking about, do you have any idea about how to do it?

2019-11-06 16:49 UTC, willjgriff approved these changes
Remove the commented test then 👍

2019-11-06 18:14 UTC, merged